### ISSUE TITLE
Why PCA?

### ISSUE THREAD

**Issue by guipotje** [Lu-Feng/CricaVPR#4]
Hi, thank you for the code!

Any specific reason the dimensionality reduction is done with PCA? I understand the flexibility of storing the PCA matrix and controlling the dimensionality after fitting, but a learnable linear projection at the end of the network may deliver better performance, did you test that?

Thanks!

**Comment by Lu-Feng** [comment]
Hello, thanks for your interest in our work. At the beginning, we chose PCA just because I followed the [benchmark repository](https://github.com/gmberton/deep-visual-geo-localization-benchmark) to implement our VPR system, which can easily add PCA to reduce dimensionality. I know that some recent work prefers to use the learnable linear projection for dimensionality reduction and has achieved good results. In recent days I have also tried adding a (10752, 4096)-linear projection at the end of the model to reduce the dimension to 4096-D. However, it seems that the model is overfitting after training. Perhaps it would be better to reduce the channel dimension from 768-D to a lower dimension beforehand, which uses a linear projection with fewer parameters. We are currently improving the dimensionality reduction in our model.

**Comment by guipotje** [comment]
Thanks for the quick reply.
I see, interesting to know a simple linear projection can overfit..
Nice to hear that you are trying to improve the dimensionality reduction! Maybe some regional pooling can help with that ? Check [this paper](https://openaccess.thecvf.com/content/ICCV2023/papers/Shao_Global_Features_are_All_You_Need_for_Image_Retrieval_and_ICCV_2023_paper.pdf) when you have some spare time, it might help somehow.
